#!/bin/ksh
#
machines="IRIX64 AIX SX6 Linux"
#
if [ ! "$storage_model" ] ; then
   if [ -d /usr/local/env/localmrb/armn/${USER} ] ; then
      storage=/usr/local/env/localmrb/armn/${USER}
   else
      echo "\n Must define environment variable storage_model"
      echo " (to store *.o *.Abs etc... on pollux) \n"
      exit
   fi
else
   storage=$storage_model
fi
ici=`true_path .`
cd $storage 2> /dev/null
if test $? != 0 ; then
  echo "\n DIRECTORY $storage does not exist \n"
  exit
fi
cd $ici
storage=${storage}/`true_path . | awk 'BEGIN{FS="/"}{print $NF}'`
#
mkdir $storage 2> /dev/null
new=`true_path $storage`
if [ "$new" = "$ici" ]; then
   same=1
else
   same=""
fi
#
for i in $machines ; do
  mainntr=main${MODEL}ntr_${i}_${MODEL_VERSION}.Abs
  maindm=main${MODEL}dm_${i}_${MODEL_VERSION}.Abs
  mkdir $storage/malib${i} 2> /dev/null
  if [ ! "$same" ]; then
    ln -sf $storage/malib${i} malib${i}
    ln -sf $storage/${mainntr} ${mainntr}
    ln -sf $storage/${maindm} ${maindm}
  fi
done
#
/bin/rm -rf process output
mkdir $storage/process $storage/output 2> /dev/null
  if [ ! "$same" ]; then
     ln -s $storage/process process
     ln -s $storage/output output
  fi
#
